import 'package:get/get.dart';


class LocalString extends Translations {
  
  @override
  Map<String, Map<String, String>> get keys => {
    'es_ES' : {
      'available_chargers' : 'Cargadores Disponibles',
      'available' : 'Disponible',
      'book' : 'Reservar',
      'charger' : 'Cargador',
      'charging_point' : 'Punto de carga',
      'choose_option' : 'Elige una opción',
      'cord.' : 'Cord.',
      'create_account' : 'Crear cuenta',
      'date' : 'Fecha',
      'description' : 'Descripción',
      'duration' : 'Duración',
      'email' : 'Email',
      'history' : 'Historial',
      'home' : 'Inicio',
      'incidences' : 'Incidencias',
      'incorrect_email_format' : 'El valor introducido no parece ser un correo',
      'insert_description' : 'Introduzca una descripción',
      'insert_email' : 'Introduce un correo electrónico',
      'insert_incidence_subject' : 'Introduce el concepto de la incidencia',
      'insert_password' : 'Introduce la contraseña',
      'language' : 'Idioma',
      'log_in' : 'Iniciar sesión',
      'logged_in' : 'Sesión iniciada',
      'not_implemented' : 'Funcionalidad no implementada',
      'optional' : '(opcional)',
      'password' : 'Contraseña',
      'passwords_dont_match' : 'Las contraseñas no coinciden',
      'repeat_password' : 'Repita la contraseña',
      'route' : 'Ruta',
      'send' : 'Enviar',
      'settings' : 'Preferencias',
      'sign_up' : 'Registrarse',
      'signed_up' : 'Registro completado',
      'start_time' : 'Hora de inicio',
      'subject' : 'Concepto',
      'wait' : 'Espere',
      'incidence_sent' : 'Se ha enviado la incidencia',
    },
    'en_UK' : {
      'available_chargers' : 'Available charging points',
      'available' : 'Available',
      'book' : 'Book',
      'charger' : 'Charger',
      'charging_point' : 'Charging point',
      'choose_option' : 'Choose an option',
      'cord.' : 'Cord.',
      'create_account' : 'Create account',
      'date' : 'Date',
      'description' : 'Description',
      'duration' : 'Duration',
      'email' : 'Email',
      'history' : 'History',
      'home' : 'Home',
      'incidences' : 'Incidences',
      'incorrect_email_format' : "The inserted value doesn't seem to be an email",
      'insert_description' : 'Insert a description',
      'insert_email' : 'Insert an email',
      'insert_incidence_subject' : 'Insert an incidence subject',
      'insert_password' : 'Insert a password',
      'language' : 'Language',
      'log_in' : 'Log in',
      'logged_in' : 'Log in completed',
      'not_implemented' : 'Funcionality not implemented',
      'optional' : '(optional)',
      'password' : 'Password',
      'passwords_dont_match' : 'Passwords do not match',
      'repeat_password' : 'Repeat password',
      'route' : 'Route',
      'send' : 'Send',
      'settings' : 'Preference',
      'sign_up' : 'Sign up',
      'signed_up' : 'Sign up completed',
      'start_time' : 'Start time',
      'subject' : 'Subject',
      'wait' : 'Wait',
      'incidence_sent' : 'The incidence has been sent',
    },
    'ca_ES' : {
      'available_chargers' : 'Carregadors Disponibles',
      'available' : 'Disponible',
      'book' : 'Reservar',
      'charger' : 'Carregador',
      'charging_point' : 'Punt de recarga',
      'choose_option' : 'Tria una opción',
      'cord.' : 'Cord.',
      'create_account' : 'Crear compte',
      'date' : 'Data',
      'description' : 'Descripció',
      'duration' : 'Duració',
      'email' : 'Email',
      'history' : 'Historial',
      'home' : 'Inici',
      'incidences' : 'Incidencies',
      'incorrect_email_format' : 'El valor introduït no pareix ser un correu',
      'insert_description' : 'Introduïu una descripció',
      'insert_email' : 'Introduïu un correu electrónic',
      'insert_incidence_subject' : 'Introduïu el concepte de la incidencia',
      'insert_password' : 'Introduïu la clau',
      'language' : 'Idioma',
      'log_in' : 'Iniciar sessió',
      'logged_in' : 'Sessió iniciada',
      'not_implemented' : 'Funcionalitat no implementada',
      'optional' : '(opcional)',
      'password' : 'Clau',
      'passwords_dont_match' : 'Les claus no coincideixen',
      'repeat_password' : 'Repeteixi la contraseña',
      'route' : 'Ruta',
      'send' : 'Enviar',
      'settings' : 'Preferencies',
      'sign_up' : 'Registrar-se',
      'signed_up' : 'Registre completat',
      'start_time' : "Hora d'inici",
      'subject' : 'Concepte',
      'wait' : 'Espere',
      'incidence_sent' : "S'ha enviat la incidencia",
    },
  };

}